#!/bin/bash
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

function banner(){
    clear
    echo -e "${turquoiseColour}########################${grayColour}#############################"
    echo -e "${turquoiseColour}#######/\######|  ___ \#${grayColour}#############################"
    echo -e "${turquoiseColour}######/  \#####| |###| |${grayColour}#| ____|#####/\##|__   __|###"
    echo -e "${turquoiseColour}#####/ /\ \####| |###| |${grayColour}#| |########/  \####| |######"
    echo -e "${turquoiseColour}####/ /##\ \###| |    /#${grayColour}#|___  |###/ /\ \###| |######"
    echo -e "${turquoiseColour}###/ /####\ \##| |#\ \##${grayColour}#####| |##/ ____ \##| |######"
    echo -e "${turquoiseColour}##/ /######\ \#| |##\ \#${grayColour}#|_____|#/ /####\ \#| |######"
    echo -e "${turquoiseColour}########################${grayColour}#############################"
}
banner
if [ $1 == "connect" ]
then
    echo -e "Contraseña >>"
    read password
    nmcli d wifi connect $2 password $password
    echo -e "Se ha conectado con exito"; read verify
    if [ $verify == "y" ]
    then
        touch /home/syltr1x/$2
        echo "SSID : $2      PWD : $password" > /home/syltr1x/$2
    elif [ $verify == "Y" ]
    then
        touch /home/syltr1x/$2
        echo "SSID : $2      PWD : $password" > /home/syltr1x/$2
    fi
elif [ $1 == "scan" ]
then
    echo -e "Starting ARSAT Scan 7.70 ( 192.168.0.1 )-( $2 ) "
    echo -e "NSE: Loaded 127 scripts for scanning network"
    echo -e "NSE: Starting runlevel 1 (of 2) scan."
    echo -e "Discovered open port 80/tcp on 192.168.0.1"; sleep 1.4
    echo -e "Discovered open port 344/wlan on 192.168.0.1"; sleep 1.2
    echo -e "Discovered open port 445/sql on 192.168.0.1"
    echo -e "NSE: Starting runlevel 2 (of 2) scan."
    echo -e "Ping send to 192.168.0.12"; sleep 0.8
    echo -e "Ping send to 192.168.0.31"; sleep 1
    if [ $2 == "complete" ]
    then
        echo -e "${redColour}[!] ALERT : EXCEPTION DETECTED${endColour}"
        echo -e "Vulnerabity Info:"
        echo -e "IP : 192.168.0.32   |   MAC : 8f:3e:00:1a:3d:9h"
        echo -e "command>"; read 
        echo -e "Are you sure want remove this dispositive?[Y/n]";read
        echo -e "Disconnecting 192.168.0.32"; sleep 1.3
        echo -e "192.168.0.32 is disconected"; sleep 0.8
        echo -e "${yellowColour}[*] Amenaza Eliminada con exito${endColour}"; sleep 0.5
        echo -e "Reiniciando el analisis de la red..."; sleep 2.3
        echo -e "${greenColour}[+] Red asegurada correctamente.${endColour}"
    elif [ $2 == "fast" ]
    then
        echo -e "${greenColour}[+] Scan complete${endColour}"
        echo -e "Amenazas: 0"
        echo -e "Fugas: 0"
        echo -e "Resumen: Red asegurada."
    else
        clear
        echo -e "Err: Falta parametro de scan."
    fi
else
    clear
    echo -e "Err: Falta parametro de ejecucion."
fi
